name: Setup Terragrunt

on: [push]

jobs:
  Setup-Terragrunt:
    name: Example Terragrunt interaction
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v1.1.0
        with:
          terragrunt_version: latest
      - name: Interact with Terragrunt
        run: terragrunt --version
      - name: Terragrunt validate
        run: terragrunt run-all plan
